name: PyLops-MPI self-hosted server 

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Installing Dependencies
        run: |
          export PATH=/global/homes/y/yuxihong/pylops-mpi-actions/install/bin:$PATH
      - name: Testing using pytest-mpi
        run: |
          srun -t 1:00:00 -N 1 -n 4 -c 64 --cpu-bind=cores -q interactive -C cpu python testmpi.py
