name: PyLops-MPI GPU Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        rank: ['2', '4']
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python environment and Install dependencies
        run: |
          python3 -m venv pylopsvenv 
          source pylopsvenv/bin/activate 
          echo $(which python3)
          echo $(which pip3)
          python3 -m pip install --upgrade pip setuptools
          pip install flake8 pytest setuptools-scm
          pip install -r requirements-dev.txt
          pip install cupy-cuda12x nvidia-nccl-cu12
      - name: Install pylops-mpi
        run: |
          source pylopsvenv/bin/activate 
          echo $(which python3)
          echo $(which pip3)
          pip install .
      - name: Testing using pytest-mpi
        run: |
          source pylopsvenv/bin/activate 
          echo $(which python3)
          echo $(which pip3)
          export PYLOPS_MPI_CUDA_AWARE=0; export TEST_CUPY_PYLOPS=1
          srun --mpi=pmix --account=yuxilab -n ${{ matrix.rank }} -N 1 --gpus=L40S:${{ matrix.rank }} pytest tests/ --with-mpi
          
